# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orashipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField()),
                ('management', models.CharField(max_length=30)),
                ('consignee', models.CharField(max_length=30)),
                ('objective', models.CharField(max_length=30)),
                ('name_emp', models.CharField(max_length=30)),
                ('driver_man', models.CharField(max_length=30)),
                ('no_car', models.CharField(max_length=30)),
                ('totel', models.CharField(max_length=30)),
                ('type_no', models.CharField(max_length=30)),
                ('Specifications', models.CharField(max_length=30)),
                ('Notes', models.CharField(max_length=200)),
            ],
        ),
    ]
